#!/bin/bash

HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_CLASS="org.sfp.lang.Parser"

# development commands to invoke scala binaries
BIN="/usr/local/opt/scala/bin/scala"
$BIN -classpath "$HOME/bin" $MAIN_CLASS $@

# invoke pure java binaries
#JAVA="java"
#JAR="$HOME/dist/sfParser.jar"
#$JAVA -jar $JAR $@
