#!/bin/bash

HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_CLASS="org.sf.lang.Parser"

#BIN="/usr/local/opt/scala/bin/scala"
#$BIN -classpath "$HOME/bin" $MAIN_CLASS $@

JAVA="java"
JAR="$HOME/dist/sfParser.jar"
$JAVA -jar $JAR $@
